language: node_js
node_js: '7'

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - COMMIT=${TRAVIS_COMMIT::8}
    - ADMIN=shows-on-demand-admin
    - ADMIN_REPO=https://github.com/guidocecilio/$ADMIN.git
    - ADMIN_USERS_DB=shows-on-demand-admin-users_db
    - ADMIN_USERS_DB_REPO=https://github.com/guidocecilio/$ADMIN.git#master:app/db

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export SECRET_KEY=my_precious
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - bash ./docker_build.sh

script:
  - docker-compose -f docker-compose-ci.yml run admin-service python manage.py initialize_db

after_script:
  - docker-compose down

after_success:
  - bash ./docker_push.sh
  - bash ./docker_deploy_prod.sh